### PR TITLE
Changes from Mailtrain project import

### PR DESCRIPTION
**Pull request by petrsiegl**
Added save and leave buttons to CUD pages.
Updated mutators handling to work with new API.
Fixed code after changes in job state API.
Updated sample jobs.
Implemented fieldsets parameter handling for jobs.

### CODE REVIEW

**Comment by petrsiegl** [comment]
No problem, can't finish it today, but will fix it ASAP in the morning.

**Comment by bures** [comment]
Perfect. Thanks.

**Comment by petrsiegl** [comment]
I just realized I added `filterData`  just to `submitFormValuesMutator` with `delete`. I will add `filterData` to all of them.

**Comment by petrsiegl** [comment]
`filterData` is now everywhere except `Develop` classes where filtering is type specific, so I kept it that way for now.

**Comment by bures** [comment]
Is this still relevant or did we bring the updates to the devel branch already? Thanks.

**Comment by petrsiegl** [comment]
It isn't, all changed should be already part of the devel branch.

**Pull request closed without merging**
